FX_LISTS = [
    {"name": "Vinyl Crackle", "path": "effects/vinyl-crackle.wav"},
    {"name": "Tape Hiss", "path": "effects/tape-hiss.wav"},
    {"name": "Rain", "path": "effects/rain.wav"},
    {"name": "Soft Rain", "path": "effects/soft-rain.wav"},
    {"name": "Heavy Rain", "path": "effects/heavy-rain.wav"},
    {"name": "Thunder", "path": "effects/thunder.wav"},
    {"name": "Distant Thunder", "path": "effects/distant-thunder.wav"},
    {"name": "Ocean Waves", "path": "effects/ocean-waves.wav"},
    {"name": "Beach Waves", "path": "effects/beach-waves.wav"},
    {"name": "Fire", "path": "effects/fire.wav"},
    {"name": "Fire Light", "path": "effects/fire-light.wav"},
    {"name": "Forest Night", "path": "effects/forest-night.wav"},
    {"name": "Birds", "path": "effects/birds.wav"},
    {"name": "Small Wind", "path": "effects/small-wind.wav"},
    {"name": "Waterfall", "path": "effects/waterfall.wav"},
    {"name": "Low Engine Hum", "path": "effects/low-engine-hum.wav"},
    {"name": "White Noise", "path": "effects/white-noise.wav"},
    {"name": "Cafe Ambience", "path": "effects/cafe-ambience.wav"},
    {
        "name": "Mechanical Keyboard Typing",
        "path": "effects/mechanical-keyboard-typing.wav",
    },
    {"name": "Computer Keyboard", "path": "effects/computer-keyboard.wav"},
    {"name": "iPhone Keyboard Typing", "path": "effects/iphone-keyboard-typing.wav"},
    {"name": "Traffic", "path": "effects/traffic.wav"},
    {"name": "Humming", "path": "effects/humming.wav"},
    {"name": "Howl In The Night", "path": "effects/howl-in-the-night.wav"},
]
